ohtutraininghub/traininghub

- Dockerfile
The public folder, containing e.g. images, was missing from the Dockerfile.
> Add the public directory to Dockerfile

- prisma/migrations/20231109172100_optional_created_by_id/migration.sql
- prisma/schema.prisma
Make `createdById` column temporarily optional so that migrations can be run for staging
> Optional createdById column 

- prisma/migrations/20231114195722_add_last_cancel_date/migration.sql
- prisma/schema.prisma
- src/app/[lang]/locales/en/app.json
- src/app/api/course/enroll/route.test.ts
- src/app/api/course/enroll/route.ts
- src/app/api/course/route.test.ts
- src/components/CourseForm/CourseForm.test.tsx
- src/components/CourseForm/CourseForm.tsx
- src/components/CourseModal/CancelEnroll.test.tsx
- src/components/CourseModal/CancelEnroll.tsx
- src/components/CourseModal/CourseModal.tsx
- src/components/CourseModal/EnrollHolder.test.tsx
- src/components/CourseModal/EnrollHolder.tsx
- src/lib/zod/courses.ts
- This PR makes it possible for admins and trainers to freely set the last date allowed to cancel one's enrollment for a course, replacing the the previous general cancellation deadline of 48 h before course start. 
- Adding a last cancellation date for a course is optional; if no last cancel date is set, a student can cancel their enrollment at any point.
- The only validation rule enforced for the last cancel date for now is that it cannot be later than the ending date of the course. Setting a last cancel date after the course start date is allowed. It is also possible to set a last cancel date in the past, to avoid validation problems if there is a need to update some other course data after the last cancellation date has passed.
- If it is past the last cancellation date for a course, …
> #162/feat/add optional last cancel date

- src/app/[lang]/admin/dashboard/CreateTag.tsx
- src/app/[lang]/admin/dashboard/page.tsx
- src/components/CourseCard/index.tsx
- src/components/CourseForm/CourseForm.tsx
- src/components/CourseList/CourseList.tsx
- src/components/CourseModal/CourseModal.tsx
- src/components/ProfileView/ProfileUserDetails.tsx
- src/components/Providers/ThemeRegistry/theme.ts
- src/components/TextEditor/MenuBar.tsx
- src/components/UnauthorizedError/index.tsx
- src/components/UserList/index.tsx
Changes MUI typography header sizes to theme. Now H1 can be used directly without specifying separately variant and component type.
Also swaps the used headers across components etc. Everything should look the same.
> MUI typography custom headers

- src/components/CourseModal/CourseModal.tsx
The modal closes now by clicking outside the modal area.
Also fixed:
- no more white borders after refresh
- modal contrast fixed (pops out from background now properly)
> Set modal to close with backdrop click

- cypress/e2e/backToTopToggle.cy.ts
- src/app/[lang]/page.tsx
- src/components/BackToTopToggle/index.tsx
Adds back to top toggle button at the bottom of the main course view.
Visible on both desktop / mobile,, however only after the screen has been scrolled down somewhat (set currently at 100px).
> Add back to top toggle

- prisma/seed.ts
The dynamically set start and end dates for courses in the seed data included non-zero seconds and milliseconds, which made the date fields in the course edit form look wonky. Now both seconds and milliseconds are reset to zero.
> Set seconds and milliseconds to zero in course seed data

- src/components/UserList/index.tsx
Modifies the function that handles the row change. 
Steps to reproduce the bug (assumed here that the db is seeded with enough users - here used the batch from seed file):
1) Open admin page.
2) With 5 rows visible go to page 2
3) Set to display 25 rows
Result:
Messes up the the pagination and shows a long empty table. Stuck there until rows is switched.
> Fix user listing pagination

- src/app/api/course/route.test.ts
- src/app/api/course/route.ts
- src/lib/auth-utils.ts
API call now checks that the current user has the required permissions to be deleting the course attempting to be deleted.
Also added a utility function to /lib/auth-utils.ts to check if user has course deletion permissions.
> #294/feat/authenticate trainer id when deleting course

- tsconfig.json
Test files had unnecessary error highlights due to Jest and Cypress conflict.
> Fix type errors in Jest test files.

- src/app/[lang]/locales/en/app.json
- src/app/[lang]/locales/en/components.json
- src/app/[lang]/profile/page.tsx
- src/components/CourseTemplateModal/EditTemplateForm.test.tsx
- src/components/CourseTemplateModal/EditTemplateForm.tsx
- src/components/CourseTemplateModal/index.test.tsx
- src/components/CourseTemplateModal/index.tsx
- src/components/EditTemplate/EditTemplateButton.test.tsx
- src/components/EditTemplate/EditTemplateButton.tsx
- src/components/ProfileView/ProfileTemplateList.test.tsx
- src/components/ProfileView/ProfileTemplateList.tsx
- src/components/ProfileView/index.tsx
- src/lib/zod/templates.ts
Created a UI part of a modal that can be used to update the template data.
The form has input fields similar to CourseForm but without the date and enrollment fields.
It has a close modal button and update button. Close modal button has a functionality but update button does not.
> #348/feat/create and add template form to modal

- src/components/CourseTemplateModal/EditTemplateForm.test.tsx
- src/components/CourseTemplateModal/EditTemplateForm.tsx
- src/components/CourseTemplateModal/index.tsx
- src/components/ProfileView/ProfileTemplateList.tsx
Created a functionality that autofills the template edit form with chosen template's data. Functionality is tested with unit tests.
> #349/feat/template edit form has template data when opened

- cypress/e2e/profileView.cy.ts
- cypress/e2e/templateEditing.cy.ts
- cypress/e2e/templateList.cy.ts
- src/app/[lang]/locales/en/components.json
- src/components/ProfileView/index.test.tsx
- src/components/ProfileView/index.tsx
The profile view now has a new tab, "My Courses" (old tab renamed to "My Enrollments"). This tab is only visible for trainers/admins. The dropdowns courses and templates created by the user have been moved here.
E2E tests involving the profile page have been amended, and now test for the visibility of the new tab.
> New profile tab for courses created by user

- src/components/CourseList/index.tsx
Grid view shows course cards next to each other without extra spacing
> Fix course card grid view

- src/app/[lang]/profile/page.tsx
- src/components/ProfileView/index.tsx
- src/lib/prisma/users.ts
Any course in profile view can now be opened as a course modal, whether the user is enrolled in the course or not. This is accomplished by making sure that the data for both sets of courses is fetched when loading the profile page.
Also added a timer to the upcoming created courses list to mirror the behaviour of upcoming enrolled courses.
> #444/fix/course modal cant be opened in profile for courses not enrolled in

- src/components/CourseForm/TemplateSelect/index.tsx
- src/components/CourseForm/index.tsx
The user can now save a template from the course editing view. 
I had to change FormType in CourseForm to always be of type CourseSchemaWithIdType for this and I'm fairly confident it didn't break anything, but just something to be aware of.
> Fix template saving in course edit view

- docs/production-setup-guide.md
- src/app/[lang]/locales/en/api.json
- src/app/api/course/request/route.ts
- src/app/api/course/route.ts
- src/app/api/slack/channel/route.test.ts
- src/app/api/slack/channel/route.ts
- src/lib/response/fetchUtil.ts
- src/lib/slack/constants.ts
- src/lib/slack/index.ts
- src/lib/zod/courses.ts
You can now make a POST request to /api/slack/channel with a Course ID to create a Slack channel for the course.
The channel name is prefixed with "tmp-traininghub-", followed by the course name in lowercase, with spaces changed to hyphens and special characters removed. The channel ID is saved to the course's slackChannelId field in the database. 
Also refactored the identical courseDeleteSchema and courseRequestSchema functions into the courseIdSchema function, which is also used in the Slack channel creation.
> Add Slack channel creation backend functionality

- src/app/[lang]/locales/en/components.json
- src/components/AttendeeTable/index.test.tsx
- src/components/AttendeeTable/index.tsx
- src/components/CourseModal/index.tsx
- src/lib/prisma/requests.ts
The UI for viewing the requests a course has received now shows timestamps for the date each request was made. The requests are ordered by the date of the request (descending).
Also added i18n integration to AttendeeTable, and created tests for the new functionality.
> Add timestamps to requesters view

- src/app/api/course/route.ts
- src/lib/slack/blocks.ts
- src/lib/slack/index.ts
If trainer chooses to send Slack notification to course participants about updated course, the message now includes the changed details. This functionality shows whether title, dates, enrollment deadlines or participant capacity of the course has been changed.
> #510/feat/add new changes to slack update message

- prisma/migrations/20240321135604_add_participation_tracking_to_database/migration.sql
- prisma/migrations/20240321155622_add_unique_constraint_to_participations/migration.sql
- prisma/schema.prisma
- src/app/[lang]/locales/en/api.json
- src/app/api/course/participation/route.test.ts
- src/app/api/course/participation/route.ts
- src/app/api/course/request/route.test.ts
- src/lib/zod/courses.ts
The database now has a table for participations, and /api/course/participation route has POST and DELETE functions implemented for adding and removing participations. Tests have been created for the API functionality.
> Add backend functionality for adding and deleting participations

- cypress/e2e/courseCreation.cy.ts
Fixed one course template test that kept failing locally in cypress. Also shortened test course's description field that potentially caused earlier timed out problems.
> #533/fix/course creation e2e test that fails from time to time

- src/app/[lang]/profile/[id]/page.tsx
- src/components/UserList/index.test.tsx
- src/components/UserList/index.tsx
The list of users on admin dashboard now contains links to /profile/[id] pages on each user. Trainers and trainees cannot access these pages. At the moment the user's page only contains ProfileUserDetails (name, email, image).
> #512/feat/create link for users in admin view
