ohtutraininghub/traininghub

src/app/page.tsx, src/components/ThemeRegistry/theme.ts
=> Update theme color palette to be usable in ssr

README.md, docs/note-on-production.md
Disclaimer regarding the scope of production environment.
Closes #58
=> #58/feat/documentation on prod

docs/CONTRIBUTING.md
Read [contribution flow](https://github.com/ohtutraininghub/traininghub/blob/%2346/feat/more-docs/docs/CONTRIBUTING.md#contribution-flow) in this branch before approving
Add suggestion changes using suggestion tag:
Closes #46
=> #46/feat/more docs

src/app/page.tsx, src/components/CourseCard/CourseCard.tsx, src/components/CourseList/CourseList.tsx
=> Course list

.dockerignore, .gitignore, Dockerfile, docker-compose.dev.yml, docker-compose.yml
- Improve Dockerfile, .dockerignore and add docker-compose.dev.yml for local testing purposes
Closes #51
=> Improve Dockerfile

package-lock.json, package.json
=> Update to latest nextjs version 13.5

.github/workflows/production.yml, .github/workflows/staging.yml
=> #99/fix/pipeline test phase

docs/CONTRIBUTING.md, scripts/dev_install.sh
Running npm run dev:install will now reset and seed the database.
=> #49: Make install-script reset and seed database

src/app/page.tsx
=> Show only current trainings

src/components/CourseModal/EditButton.tsx
Fixes a problem where the link is clickable from outside the edit button
=> Fix edit button link width

src/components/CourseFilter/CourseFilter.tsx
#94 Fixes the issue where the datepicker clears all the filters when the date range is cleared.
=> Fix datepicker

.dockerignore, Dockerfile
Deploy job still throws errors about not finding /app/public-folder
=> Attempt to fix missing public folder in builder stage

package-lock.json, src/middleware.ts
- fix sentry tunnel with middleware
- security update sentry
=> Hotfix sentry tunnel

package-lock.json, package.json, src/app/[lang]/locales/en/components.json, src/components/TextEditor/MenuBar.tsx, src/components/TextEditor/MenuBarItem.tsx, src/components/TextEditor/ResizeExtension.tsx, src/components/TextEditor/index.tsx, src/components/TextEditor/urlPrompt.tsx, src/lib/zod/links.ts
This PR:
- Adds support for images from external sources
- Images can be rearranged and resized
- Adds option to align text / images on the x-axis
- Improved link and url prompts
- Other minor visual improvements with the toolbar
=> Images to course description

.github/workflows/staging.yml, cypress.config.ts, cypress/e2e/adminView.cy.ts, cypress/e2e/backToTopToggle.cy.ts, prisma/seed.ts, src/app/[lang]/locales/en/admin.json, src/components/UserList/index.test.tsx, src/components/UserList/index.tsx
=> #199/feat/pagination and search to user list

src/components/ProfileMenu/index.tsx
- Make avatar icon little bit smaller to fit nicely into the navbar
- Change icon button border radius and padding to make the hover shadow shape match the button
=> Improve profile button styling

src/app/[lang]/course/[id]/edit/page.tsx, src/app/[lang]/course/page.tsx, src/app/api/course/route.ts, src/components/CourseModal/CourseModal.tsx, src/lib/auth-utils.ts
=> #225/feat/make it possible for trainer to edit any course

src/app/api/course/route.test.ts, src/lib/auth-utils.ts
Small addition to the backend code to allow admins to delete any training
=> #330/feat/admin can delete any training

src/app/[lang]/locales/en/components.json, src/components/EditTemplate/EditTemplateButton.test.tsx, src/components/EditTemplate/EditTemplateButton.tsx, src/components/ProfileView/ProfileTemplateList.tsx
This adds an edit template button to the profile page view. This button is responsive and scale with smaller screens. No functionality in this PR.
=> #337/feat/edit template button frontend

src/app/api/course/route.ts, src/lib/google/index.ts, src/lib/prisma/calendar.ts
This feature removes calendar events from google calendar when course is deleted.
Co-contributor: akskokki
=> #357/feat/remove calendar events when course is deleted

src/components/CourseTemplateModal/index.test.tsx, src/components/CourseTemplateModal/index.tsx, src/components/EditTemplate/EditTemplateButton.test.tsx, src/components/EditTemplate/EditTemplateButton.tsx, src/components/ProfileView/ProfileTemplateList.test.tsx, src/components/ProfileView/ProfileTemplateList.tsx
Created an empty template modal and added functionality to open the modal by clicking the edit button in the profile view.
=> #337/feat/coursetemplate modal

cypress/e2e/courseCreation.cy.ts, src/components/CourseForm/TemplateSelect/index.tsx, src/components/CourseForm/index.test.tsx, src/components/CourseForm/index.tsx, src/components/TextEditor/MenuBar.tsx, src/components/TextEditor/index.tsx
The text editor in CourseForm is now fixed
=> #336/fix/description text editor fix

src/components/CourseModal/index.tsx, src/components/CourseTemplateModal/index.tsx, src/components/Providers/ThemeRegistry/theme.ts
Added modal backdrop colour to theme colour palette and replaced hard-coded values in CourseModal and CourseTemplateModal
=> #368/fix/add modal background color to theme colour palette

src/components/CourseForm/index.test.tsx, src/components/CourseForm/index.tsx
Created new unit tests for creating and editing courses. Also did a little bit of refactoring for the old tests.
=> #376/fix/unit tests for courseform

src/components/ProfileView/ProfileTemplateList.test.tsx
Made small fixes to make the tests work
=> #382/fix/fix profile template list tests

src/app/[lang]/locales/en/components.json, src/components/ProfileView/index.test.tsx, src/components/ProfileView/index.tsx
Created a dropdown UI component that shows trainer's or admin's created courses that have ended. This UI component already fetches the past courses from the database (so the task #391 was automatically implemented along with this task).
=> #393/feat/create dropdown UI component

cypress/e2e/profileView.cy.ts, prisma/seed.ts, src/components/ProfileView/ProfileCourseList.test.tsx, src/components/ProfileView/ProfileCourseList.tsx, src/components/ProfileView/index.tsx
Created E2E tests for the user story #388 and for the ProfileView in general
=> #392/feat/E2E tests for 388

scripts/dev_install.sh, src/lib/slack/index.ts, src/lib/timedateutils.ts
Added sendCoursePoster function to 'lib/slack'. Also added SLACK_BOT_TOKEN and HOST_URL to .env file script
=> #410/feat/create a function to post course details into slack

cypress/e2e/profileView.cy.ts
Created E2E tests for the user story #285 .
=> #395/feat/e2 e tests for 285

src/app/api/course/enroll/route.ts, src/lib/slack/index.ts
Slack lib file now has function that composes and sends a "course full"-notification to the specified user.
Slack notification is now automatically attempted to be sent to the Slack user matching the email of the course creator when course is at max enrollment capacity. (This completes task https://github.com/ohtutraininghub/traininghub/issues/399)
=> 400 if course becomes full send slack notif to trainer

.github/workflows/heroku-deploy.yml
=> Add HOST_URL and SLACK_BOT_TOKEN to docker build args

.github/workflows/heroku-deploy.yml
=> Add HD_HOST_URL and HD_SLACK_BOT_TOKEN

src/lib/slack/blocks.ts
Removed use of course.description in createBlockNewTraining and replaced it with a string
=> Replaced description with string

src/lib/slack/constants.ts, src/lib/slack/index.ts
Slack lib sendCoursePoster now has a function to check if channel exists before trying to send message to Slack channel
=> Add check if channel exists

docs/production-setup-guide.md
This pull request contains information how to setup slack
=> #469/feat/add information how to setup slack

src/app/[lang]/page.tsx, src/components/CourseFilter/CourseFilterLogic.ts, src/components/CourseFilter/index.test.tsx, src/components/CourseList/index.test.tsx, src/components/CourseList/index.tsx, src/components/CourseModal/index.test.tsx, src/lib/prisma/courses.ts, src/lib/prisma/users.ts
Added request training view and completely absent tests for CourseList component.
=> #402/feat/create request training view

src/app/api/course/route.ts, src/lib/prisma/users.ts, src/lib/slack/blocks.ts, src/lib/slack/index.ts
Feature that sends a direct Slack message when a course is deleted and the user has been enrolled in that course.
Task #462 was also implemented here.
=> #461/feat/add slack util function for sending notification

cypress/e2e/profileView.cy.ts, src/components/ProfileView/ProfileCourseList.tsx, src/components/ProfileView/index.test.tsx, src/components/Providers/ThemeRegistry/theme.ts
This feature turns timer green when course is in progress
=> #466/feat/timer element changes to inprogress

src/components/CourseForm/TemplateSelect/index.test.tsx
Minor fix to get the unit test logs clean
=> fix test error in template select

cypress/e2e/courseEditing.cy.ts, src/components/CourseForm/index.tsx, src/components/CourseModal/EditButton.tsx, src/lib/zod/courses.ts
Course editing has been fixed. They had broken when a new field was added to the course schema in the database.
Added e2e tests for course editing to catch bugs earlier in the future.
=> Fix course editing

src/app/[lang]/locales/en/components.json, src/app/[lang]/page.tsx, src/components/Buttons/Buttons.tsx, src/components/CourseList/index.tsx, src/components/CourseModal/index.test.tsx, src/components/CourseModal/index.tsx
Created handlers for requesting a course and removing the request. Handler and corresponding text are passed for the button depending on whether the user has already requested the course or not.
=> #405/feat/handlers for request button

src/app/api/course/route.ts, src/lib/slack/constants.ts, src/lib/slack/index.ts
Added a slack util function that archives a Slack channel when given channel id and name. Before archiving the channel the archiveChannel function calls renameChannel function that adds month at the end of the channel's name. This is needed to avoid future conflicts when trying to create a course with same name.
=> #463/feat/slack util function for archiving channel

cypress/e2e/courseRequest.cy.ts, cypress/e2e/profileView.cy.ts, prisma/seed.ts, src/components/Buttons/Buttons.tsx, src/components/CourseCard/index.tsx, src/components/CourseModal/index.tsx
e2e tests for story #78 requests
=> #407/feat/78 e2e

src/app/api/course/route.ts, src/lib/slack/index.ts
Now archiveChannel is called when course is deleted. In addition refactored some indistinct parameter names and functions that had duplicate code.
=> #464/feat/call function when course is deleted

src/app/api/slack/channel/route.ts, src/lib/prisma/users.ts, src/lib/slack/constants.ts, src/lib/slack/index.ts
You can now add all enrolled users to slack channel while creating it.
=> #457/feat/add participants to channel function

prisma/migrations/20240320102906_add_countries_and_titles/migration.sql, prisma/migrations/20240320131109_update_country_and_title_relations/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/UserList/index.tsx, types/next-auth.d.ts
Database now has new tables for countries and titles. Also User table has now columns for country, title and profileCompleted
=> #517/feat/create db columns user and table entries for country and role

src/app/[lang]/locales/en/components.json, src/components/AttendeeTable/index.test.tsx, src/components/AttendeeTable/index.tsx
Created checkboxes beside each attendee's name in the table in course modal's students view. There was no need to create separate save button since in the future, the checkbox value will be connected straight to database.
=> #505/feat/add checkboxes and save button to UI

src/app/api/course/participation/route.ts, src/components/AttendeeTable/index.test.tsx, src/components/AttendeeTable/index.tsx, src/components/CourseModal/index.test.tsx, src/components/CourseModal/index.tsx, src/lib/prisma/requests.ts, src/lib/prisma/users.ts
Clicking the checkboxes in the attendees view now changes their participation status for the course in the database.
=> Frontend functionality for marking participants

cypress/e2e/courseParticipation.cy.ts
=> #509/feat/e2e tests for 184

cypress/e2e/adminView.cy.ts, prisma/seed.ts, src/app/[lang]/admin/dashboard/page.tsx, src/app/[lang]/locales/en/admin.json, src/app/[lang]/profile/page.tsx, src/components/ProfileView/index.test.tsx, src/components/ProfileView/index.tsx, src/components/UserList/index.test.tsx, src/components/UserList/index.tsx
Admin dashboard now has dropdowns which will enable an admin to change each user's country or title. Functionality not yet implemented.
Also added countries and titles for each user in the dev environment seed data.
=> #522/feat/add dropdowns to admin dashboard

cypress/e2e/adminView.cy.ts, src/components/UserList/index.test.tsx, src/components/UserList/index.tsx
Added handlers for submitting the changed country/title data to the database.
=> #523/feat/add frontend functionality to user country title editing

cypress/e2e/completeProfile.cy.ts, prisma/seed.ts, src/components/SelectDropdown/index.tsx
End to end tests for complete profile information feature
=> #519/feat/e2e for profile completion

src/components/CompleteProfile/index.tsx
=> Fix rerouting issue

src/components/CompleteProfile/index.tsx
=> Redirect issue fix
